version: '3.4'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=messenger
      - POSTGRESQL_PASSWORD=messenger12345
      - POSTGRESQL_DATABASE=messenger
    volumes:
      - pgdata:/bitnami
    networks:
      - svcnw

  messenger:
    image: messenger
    restart: always
    build:
      context: .
      dockerfile: ./messenger_api/Dockerfile
    ports:
      - '5005:80'
    networks:
      - svcnw
    depends_on:
      - postgresql

volumes:
  pgdata:
 
networks:
  svcnw:
    driver: bridge